# Generated by Django 3.2.10 on 2022-07-12 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0003_auto_20220712_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
